/*
자동차 종류: 세단 OR SUV
대여 가능: 2022-11-01 ~ 2022-11-30
30일간의 대여 금액: 50만 이상 200만 미만
조회: CAR_ID, CAR_TYPE, 대여금액 FEE
정렬: FEE DESC, CAR_TYPE ASC, CAR_ID DESC
*/

-- 코드를 입력하세요
SELECT *
FROM (
        SELECT C.CAR_ID
             , C.CAR_TYPE
             , TRUNC(C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100) AS FEE
        FROM CAR_RENTAL_COMPANY_CAR C
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE
        WHERE 1 = 1
        AND C.CAR_TYPE IN ('세단', 'SUV')
        AND D.DURATION_TYPE = '30일 이상'
) B
WHERE 1 = 1
AND NOT EXISTS (
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE 1 = 1
    AND H.CAR_ID = B.CAR_ID
    AND H.START_DATE <= DATE '2022-11-30'
    AND H.END_DATE >= DATE '2022-11-01'
)
AND FEE >= 500000
AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC