/*
FOOD_PRODUCT -- 식품
FOOD_ORDER -- 주문
생산일자:202205
식품ID, 식품이름, 총매출(P.PRICE*O.AMOUNT)
총매출 내림차순, 식품ID 오름차순
*/
-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P
LEFT OUTER JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE 1 = 1
AND TO_CHAR(O.PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC