-- 코드를 입력하세요
SELECT FLAVOR
FROM (
        SELECT F.FLAVOR AS FLAVOR
             , SUM(F.TOTAL_ORDER + J.TOTAL_ORDER) AS TOTAL_ORDER
        FROM FIRST_HALF F
        LEFT OUTER JOIN JULY J ON F.FLAVOR = J.FLAVOR
        GROUP BY F.FLAVOR
        ORDER BY TOTAL_ORDER DESC
     )
WHERE ROWNUM <= 3