-- 2022년 1월 기준
-- 저자별, 카테고리별 매출액 TOTAL_SALES = 판매량 * 판매가
-- 저자 ID 오름차순, 카테고리 내림차순
SELECT A.AUTHOR_ID
     , A.AUTHOR_NAME
     , B.CATEGORY
     , SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B
LEFT OUTER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
LEFT OUTER JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE TO_CHAR(S.SALES_DATE, 'YYYYMM') = '202201'
GROUP BY A.AUTHOR_ID
     , A.AUTHOR_NAME
     , B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC

