/*
-- 조회: HOUR, COUNT
-- 조건: 0시부터 23시 각 시간대별로
-- 정렬: 시간대 순으로
*/
-- 코드를 입력하세요
SELECT H.HOUR AS HOUR
     , NVL(A.COUNT, 0) AS COUNT
FROM (
    SELECT LEVEL - 1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
) H
LEFT JOIN (
    SELECT EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) AS HOUR
         , COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP))
) A ON H.HOUR = A.HOUR
ORDER BY H.HOUR