-- 코드를 입력하세요
/*
- 조회: 년, 월, 성별, 회원 수
- 정렬: 년, 월, 성별 오름차순
- 예외: 성별 없으면 결과 제외
*/
-- 숫자형으로 날짜 가져올 때는 EXTRACT 사용
SELECT EXTRACT(YEAR FROM O.SALES_DATE) AS YEAR
     , EXTRACT(MONTH FROM O.SALES_DATE) AS MONTH
     , U.GENDER
     , COUNT(DISTINCT U.USER_ID) AS USERS
FROM USER_INFO U
JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID 
WHERE U.GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM O.SALES_DATE)
       , EXTRACT(MONTH FROM O.SALES_DATE)
       , U.GENDER
ORDER BY YEAR, MONTH, GENDER