/*
조건: 리뷰를 가장 많이 작성한 1명
조회: M.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE
정렬: R.REVIEW_DATE, R.REVIEW_TEXT
*/
-- 코드를 입력하세요
SELECT M.MEMBER_NAME
     , R.REVIEW_TEXT
     , TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
WHERE 1 = 1
AND M.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM (
        SELECT T.MEMBER_ID, COUNT(*) AS CNT
        FROM REST_REVIEW T
        GROUP BY T.MEMBER_ID
        ORDER BY CNT DESC
        )
    WHERE ROWNUM = 1
)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT