/*
- 조회: D.DEPT_ID, D.DEPT_NAME_EN, ROUND(AVG(E.SAL)) AS AVG_SAL
- 정렬: AVG_SAL DESC
- 테이블: HR_DEPARTMENT D HR_EMPLOYEES E
*/

SELECT D.DEPT_ID
     , D.DEPT_NAME_EN
     , ROUND(AVG(E.SAL)) AS AVG_SAL
FROM HR_DEPARTMENT D
JOIN HR_EMPLOYEES E ON D.DEPT_ID = E.DEPT_ID
GROUP BY D.DEPT_ID
ORDER BY AVG_SAL DESC
