/*
조건: 들어올 때는 중성화 X = Intact, 나갈 때는 중성화
조회: ANIMAL_ID, ANIMAL_TYPE, NAME
정렬: ANIMAL_ID
*/

SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS O 
JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE 1 = 1
AND SUBSTR(I.SEX_UPON_INTAKE, 1, INSTR(I.SEX_UPON_INTAKE, ' ') - 1) = 'Intact'
AND SUBSTR(O.SEX_UPON_OUTCOME, 1, INSTR(O.SEX_UPON_OUTCOME, ' ') - 1) IN ('Spayed', 'Neutered')
ORDER BY O.ANIMAL_ID